### PR TITLE
Add CNVR and GEXP feature name converter as a python module

### PR DESCRIPTION
**Pull request by jordan2lee**
adds python module to convert gene expression entrez IDs to TMP project feature nomenclature. 

adds python module to convert copy number gene symbols to TMP project feature nomenclature

moves reference files (for mapping user data to TMP nomenclature ) from github and instead stored on Synapse (and soon the publication page). updated README to reflect this change and direct users to download file

### CODE REVIEW

**Comment by briankarlberg** [comment]
READMEs currently refer to `convert.py` instead of `tmp_convert.py`

GDAN-TMP specific gene IDs are HUGOs, correct? Entrez IDs are indicated as a source format in the BRCA METABRIC tutorial, could add clarity to state that the target gene ID format is HUGO within the GDAN-TMP specific format.

Sentence two in the root readme 'Users can run predictions on their molecular data.' could possibly be improved with something like 'Users can run models to make predictions on their molecular data.' or 'Users can predict cancer subtypes with their molecular data.'

**Comment by jordan2lee** [comment]
> READMEs currently refer to convert.py instead of tmp_convert.py

Updated with commit [239fb14](https://github.com/NCICCGPO/gdan-tmp-models/pull/48/commits/239fb148132a3071ab2afef7ff20ff66f83966fe)

> Sentence two in the root readme 'Users can run predictions on their molecular data.' could possibly be improved with something like 'Users can run models to make predictions on their molecular data.' or 'Users can predict cancer subtypes with their molecular data.'

Great suggestion, we want the use case of this tool to be very clear. Updated in commit [2a06b8a](https://github.com/NCICCGPO/gdan-tmp-models/pull/48/commits/2a06b8a9323e2a6d54b9abb334d3023a5f4b35d0)

**Comment by jordan2lee** [comment]
> GDAN-TMP specific gene IDs are HUGOs, correct? Entrez IDs are indicated as a source format in the BRCA METABRIC tutorial, could add clarity to state that the target gene ID format is HUGO within the GDAN-TMP specific format.

This is a subtle change where gene expression is currently in Entrez, while copy number is in Hugo gene symbol. This is due to source files provided by the GDC are only in Hugo. Due to not always 1:1 mapping when map backwards from Hugo to Entrez, it is in Hugo for cnvr conversion

**Comment by briankarlberg** [comment]
Review complete, please merge or cancel additional review request / verify users with write access to merge

**Pull request merged**
